### ISSUE TITLE
"?" dans un commentaire

### ISSUE THREAD

**Issue by DaPo** [Darklg/CSSLisible#80]
**Source**
```css
// Fake-select ?

.test {
    margin: 0;
}
```

**Résultat obtenu :**

```css
// Fake-select ?.test {
    margin: 0;
}
```

:love_hotel:
