### ISSUE TITLE
Compatibilité CSS Variables

### ISSUE THREAD

**Issue by CyrilKrylatov** [Darklg/CSSLisible#90]
Je ne suis pas sûr à quel point cela est important, à toi de le définir, mais personnellement j'aime bien avoir mes déclarations de variables avant tout le reste.

Actuellement, CSSLisible formate de la manière suivante :

```css
.bloc {
    padding-right: var(--gutter-XXL);
    padding-left: var(--gutter-XXL);
    --gutter-XXL: calc(var(--gutter-L) * 2);
}
```
J'aurai préféré, pour peut-être plus de clarté : 

```css
.bloc {
    --gutter-XXL: calc(var(--gutter-L) * 2);
    padding-right: var(--gutter-XXL);
    padding-left: var(--gutter-XXL);
}
```

C'est également ce que je vois dans la plupart des articles sur le sujet.
