### ISSUE TITLE
`@supports` not CSSLisible-ised properly

### ISSUE THREAD

**Issue by CyrilKrylatov** [Darklg/CSSLisible#91]
Hi dear,

I have a minor issue with `@supports` property.

Original code: 

```css
@supports (-webkit-backdrop-filter: blur(1px))or(backdrop-filter:blur(1px) ) {div { border: 1px red solid;}}
```

Result after CSSLisible:

```css
@supports(-webkit-backdrop-filter:blur(1px) )or(backdrop-filter:blur(1px) ) {
  div {
    border: 1px red solid;
  }
}
```

Expected after CSSLisible:

```css
@supports (-webkit-backdrop-filter: blur(1px)) or (backdrop-filter:blur(1px)) {
  div {
    border: 1px red solid;
  }
}
```

Thank you 😘
