### ISSUE TITLE
`@media(prefers-reduced-motion:reduce)` nos CSSLisibled properly

### ISSUE THREAD

**Issue by CyrilKrylatov** [Darklg/CSSLisible#92]
Hi chaton 

I have kind of the same issue with #91 about `@media (prefers-reduced-motion: reduce)`.

Original code:

```css
@media (prefers-reduced-motion:reduce) {
  div {
    border: 1px red solid !important;
  }
}
```

After CSSLisible:

```css
@media(prefers-reduced-motion:reduce) {
  div {
    border: 1px red solid !important;
  }
}
```

Expected result:

```css
@media (prefers-reduced-motion: reduce) {
  div {
    border: 1px red solid !important;
  }
}
```

Cheers m8
