### ISSUE TITLE
Put `grid` flingued API below `display: grid;`

### ISSUE THREAD

**Issue by CyrilKrylatov** [Darklg/CSSLisible#93]
Hi chaton,

As flex properties are CSSLisibled below `display: flex;` I would expect to have the same for CSS Grid API.

For example, before CSSLisible:

```css
.body {
  display: grid;
  align-items: center;
  grid-auto-flow: column;
  justify-content: flex-end;
  margin: 55px 0 calc(var(--gutter-L) * 2);
  font-size: 16px;
  grid-gap: var(--gutter-S);
  font-weight: 600;
  color: #fff;
  grid-template-columns: repeat(3,min-content);
}
```

After CSSLisible:

```css
.body {
  display: grid;
  align-items: center;
  justify-content: flex-end;
  margin: 55px 0 calc(var(--gutter-L) * 2);
  font-size: 16px;
  font-weight: 600;
  color: #fff;
  grid-auto-flow: column;
  grid-gap: var(--gutter-S);
  grid-template-columns: repeat(3,min-content);
}
```

Expected:

```css
.body {
  display: grid;
  grid-template-columns: repeat(3,min-content);
  grid-auto-flow: column;
  grid-gap: var(--gutter-S);
  align-items: center;
  justify-content: flex-end;
  margin: 55px 0 calc(var(--gutter-L) * 2);
  font-size: 16px;
  font-weight: 600;
  color: #fff;
}
```

And so on for all the `grid` properties.

Thanks and take care,

love,

tati
