### ISSUE TITLE
`gap` shorthand

### ISSUE THREAD

**Issue by CyrilKrylatov** [Darklg/CSSLisible#94]
Bonsoir,

Est-ce que ça ne serait pas malin de shorthand les propriétés `row-gap` et `column-gap` en `gap` ?

Par exemple : 

```css
.element {
  row-gap: 10px;
  column-gap: 15px;
}
```

deviendrait :

```css
.element {
  gap: 10px 15px;
}
```

donc, `gap: <row-gap> <column-gap>`

Merci d'avance, bàt, bises
