### ISSUE TITLE
CSSLisible is removing some things within `background` shorthand

### ISSUE THREAD

**Issue by CyrilKrylatov** [Darklg/CSSLisible#95]
Before: 

```css
div {
  background: transparent url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="11.5" fill="%23fff" stroke="%23000" transform="matrix(-1 0 0 1 24 0)"/><path fill="%23000" d="m13.06 8 .94.94L10.947 12 14 15.06l-.94.94-4-4 4-4Z"/></svg>') center no-repeat;
```

After:
```css
div {
  background: transparent url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" aria-hidden="true" focusable="false"><circle cx="12" cy="12" r="11.5" fill="%23fff" stroke="%23000" transform="matrix(-1 0 0 1 24 0) "/>') center no-repeat;
}
```

As you can see the `</svg>`  at the end of the the `url()` parameter is removed. The `<path />` tag is also removed.

I've made you a diff there: https://www.diffchecker.com/Q96oT0C1/

Cheers me m8,
