### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by CyrilKrylatov** [Darklg/CSSLisible#96]
Input:

```scss
.single-image {
  @include media-breakpoint-up(md) {
    max-width: 300px;
  }
  & { 
max-height: 169px;
  max-width: 100%;
}
}
```

output: 

```scss
.single-image {
    @include media-breakpoint-up(md) {
    max-width: 300px;
  }

  & {
    max-height: 169px;
    max-width: 100%;
  }
}
```

expected:

```scss
.single-image {
  @include media-breakpoint-up(md) {
    max-width: 300px;
  }

  & {
    max-height: 169px;
    max-width: 100%;
  }
}
```

bàv
